// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using achiev_hub.Server.Infrastructure.Persistence;

#nullable disable

namespace achiev_hub.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001001100_AddUserSyncStatus")]
    partial class AddUserSyncStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model is maintained in ApplicationDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
