// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using achiev_hub.Server.Infrastructure.Persistence;

#nullable disable

namespace achiev_hub.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001020000_AddUserSyncPipelineStage")]
    partial class AddUserSyncPipelineStage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model is maintained in ApplicationDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
