// <auto-generated />
using achiev_hub.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace achiev_hub.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260930145500_WidenGameAndAchievementNameColumns")]
    partial class WidenGameAndAchievementNameColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is tracked in ApplicationDbContextModelSnapshot.
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0");
#pragma warning restore 612, 618
        }
    }
}
